#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 17 16:33:41 2023

@author: matislrd
"""

"""
TU Berlin
Einführung in die Informationstechnik für Ingenieure

Vorgaben zu Aufgabe 05 - Kontrollstrukturen II
"""

mix = [51, 0, "Q", "LISTE", 4.3, {"null" : 0, "eins" : 1, "zwei" : 2}, -1, "Tupel", 1, "False", 3 > 5, "hell", 666, "dictionaries", True, 42.42]

# START TODO ###################

#Integer
integers = []
for element in mix:
    if type(element) == int:
        integers += [element]

print("ints == ", integers)

     



# END TODO #####################


