#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 17 16:33:41 2023

@author: matislrd
"""

"""
TU Berlin
Einführung in die Informationstechnik für Ingenieure

Vorgaben zu Aufgabe 05 - Kontrollstrukturen II
"""

mix = [51, 0, "Q", "LISTE", 4.3, {"null" : 0, "eins" : 1, "zwei" : 2}, -1, "Tupel", 1, "False", 3 > 5, "hell", 666, "dictionaries", True, 42.42]

# START TODO ###################

ints = []
floats = []
strings = []
dicts = []
doubles = []
for element in mix:
    if type(element) == int:
        ints += [element]
    elif type(element) == float:
        floats += [element]
    elif type(element) == str:
        strings += [element]
    elif type(element) == dict:
        dicts += [element]
    elif type(element) == bool:
        break

# END TODO #####################
# Ausgaben der Listen
print("Sortierte Listen: ")
print(ints)
print(doubles)
print(strings)
print(dicts)

# Ausgabe der Summe von allen eingelesenen Zahlen
print(summe)

